apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask-deployment
  labels:
    app: hello-flask
  namespace: ingress-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-flask
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
      - image: 044403692004.dkr.ecr.ap-northeast-2.amazonaws.com/hello-flask
        imagePullPolicy: Always
        name: hello-flask
        resources:
          requests:
            cpu: "100m"
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
      nodeSelector:
        nodegroup-type: "backend-node-group"