apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask-deployment
  labels:
    app: hello-flask
#name space change 
  namespace: nodeport-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-flask
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
      - image: iml1111/hello_flask
        imagePullPolicy: Always
        name: hello-flask
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
#add nodeSelector
      nodeSelector:
        nodegroup-type: "managed-frontend-workloads"
        
