apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-flask-hpa
  namespace: nodeport-sample
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-flask-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50